<?php


namespace App\Form;


use App\Entity\Ad;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdType extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options) {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder
            ->add('id', null, ['label' => 'Номер объявления', 'disabled' => true])
            ->add('title', null, ['label' => 'Заголовок'])
            ->add('content', TextareaType::class, ['label' => 'Содержание']);
    }

    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults([
            'data_class' => Ad::class
        ]);
    }

}